# Generated by Django 3.2.13 on 2022-09-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('authors', models.TextField()),
                ('publishDate', models.CharField(max_length=100)),
                ('imageLink', models.TextField()),
            ],
        ),
    ]
