# Generated by Django 3.2.13 on 2022-09-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='genres',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
